# Generated by Django 3.0.5 on 2020-04-17 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('old', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='账户')),
                ('name', models.CharField(max_length=8, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('telephone', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='手机号')),
                ('address', models.CharField(max_length=50, verbose_name='住址')),
            ],
            options={
                'verbose_name': '职员',
                'verbose_name_plural': '职员',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='职称')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='房间号')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Emp', verbose_name='负责职员')),
                ('old', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='old.Old', verbose_name='入住老人')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
            },
        ),
        migrations.AddField(
            model_name='emp',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Position', verbose_name='职位'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='采购日期')),
                ('money', models.DecimalField(decimal_places=4, max_digits=32, verbose_name='金额')),
                ('content', models.TextField(verbose_name='内容')),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Emp', verbose_name='采购负责人')),
            ],
            options={
                'verbose_name': '采购账单',
                'verbose_name_plural': '采购账单',
            },
        ),
    ]
