# Generated by Django 3.0.5 on 2020-05-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='old',
        ),
    ]
