# Generated by Django 3.0.5 on 2020-05-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0002_old_room'),
        ('employee', '0003_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='employee.Emp', verbose_name='负责职员'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('正在使用', '正在使用'), ('未使用', '未使用')], default='未使用', max_length=10, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('status', models.CharField(max_length=50, verbose_name='状态')),
                ('comment', models.TextField(verbose_name='评价')),
                ('mark', models.FloatField(verbose_name='评分')),
                ('old', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='老人', to='old.Old')),
            ],
        ),
    ]
