# Generated by Django 3.0.5 on 2020-05-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200512_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderform',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterField(
            model_name='orderform',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='mark',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='评分'),
        ),
    ]
