# Generated by Django 3.0.5 on 2020-05-13 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200513_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
    ]
