# Generated by Django 3.0.5 on 2020-05-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_orderform_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='company_id',
            field=models.IntegerField(default=1, verbose_name='机构id'),
            preserve_default=False,
        ),
    ]
