# Generated by Django 3.0.5 on 2020-05-02 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('name', models.CharField(max_length=50, verbose_name='企业名')),
                ('tp', models.CharField(max_length=20, verbose_name='类型')),
                ('telephone', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='手机号')),
                ('address', models.CharField(max_length=50, verbose_name='住址')),
                ('introduce', models.TextField(verbose_name='介绍')),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业',
            },
        ),
    ]
