# Generated by Django 3.0.5 on 2020-05-04 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('content', models.TextField(verbose_name='介绍')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='tp',
            field=models.CharField(choices=[('餐饮', '餐饮'), ('医护', '医护'), ('心理咨询', '心理咨询')], max_length=20, verbose_name='类型'),
        ),
    ]
