# Generated by Django 3.0.5 on 2020-05-13 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200513_0154'),
        ('old', '0002_old_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olds', to='employee.Room'),
        ),
    ]
