# Generated by Django 3.0.5 on 2020-05-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_orderform_company_id'),
        ('old', '0003_auto_20200513_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old',
            name='room',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olds', to='employee.Room'),
        ),
    ]
